export const projects = [
  {
    _id: "630120134042e2d798b59dd6",
    title: "Angular Portfolio",
    techUsed: "Angular, RxJS, Bootstrap",
    desc: "Personal portfolio made in Angular",
    img: "/images/portfolio.jpg",
    link: "https://affanhakak.netlify.app/",
  },
  {
    _id: "630120134042e2d798b59dd5",
    title: "Task Manager",
    techUsed: "Angular, Angular Material, Bulma, RxJS",
    desc: "A task management app to keep track of your day today tasks",
    img: "/images/task_mgr.jpg",
    link: "https://task-manager-ah.netlify.app/",
  },
  {
    _id: "630120134042e2d798b59dd4",
    title: "E-com Dummy",
    techUsed: "Angular, RxJS, Bootstrap",
    desc: "A dummy E-Commerce app with a functional cart to add and remove items",
    img: "/images/shoppy.jpg",
    link: "https://demo-ecom-ah.netlify.app/",
  },
  {
    _id: "630120134042e2d798b59dd3",
    title: "Score Keeper",
    techUsed: "Vanilla Javascript",
    desc: "A score keeper app to keep track of scores of two teams or two players",
    img: "/images/score.jpg",
    link: "https://scorekeeperah.netlify.app/",
  },
//   {
//     _id: "630120134042e2d798b59dd2",
//     title: "TV Search App",
//     techUsed: "Vanilla Javascript",
//     desc: "An external api app in which data is fetched",
//     img: "/images/tv.jpg",
//     link: "https://tvsearchappah.netlify.app/",
//   },
  {
    _id: "630120134042e2d798b59dd1",
    title: "Dashboard Demo",
    techUsed: "Angular",
    desc: "A simple dashboard on which content can be populated and removed",
    img: "/images/dash.jpg",
    link: "https://demo-dash-ah.netlify.app/",
  },
//   {
//     _id: "630120134042e2d798b59dd0",
//     title: "Simple Calci",
//     techUsed: "Vanilla JS",
//     desc: "A calculator to perform basic mathematical operations",
//     img: "/images/calculator.jpg",
//     link: "https://calciah.netlify.app/",
//   },
];
